# Generated by Django 2.2.1 on 2019-05-04 15:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('memory_of', models.BooleanField(default=False)),
                ('memory_of_type', models.CharField(blank=True, choices=[(1, 'In Honor Of'), (2, 'In Memory Of')], max_length=255, null=True)),
                ('first_name_memory', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_memory', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('from_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('message_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_first_name', models.CharField(max_length=255)),
                ('cc_last_name', models.CharField(max_length=255)),
                ('bill_street', models.CharField(max_length=255)),
                ('bill_city', models.CharField(max_length=255)),
                ('bill_zip', models.CharField(max_length=255)),
                ('bill_apt', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_state', models.CharField(max_length=255)),
                ('bill_country', models.CharField(max_length=255)),
                ('monthly_gift', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
