# Generated by Django 2.2.1 on 2019-05-06 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='bill_apt',
            new_name='name_on_card',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bill_city',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bill_country',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bill_state',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bill_street',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bill_zip',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cc_first_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cc_last_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='first_name_memory',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='from_notification',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='full_name_notification',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_name_memory',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='memory_of',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='memory_of_type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='message_notification',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='monthly_gift',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='recipient_notification',
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
