# Generated by Django 2.2.1 on 2019-05-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_donation_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='raised',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='supporters',
        ),
    ]
