# Generated by Django 2.2.1 on 2019-05-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190513_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
