import random
from django.core.management.base import BaseCommand
from reading.models import Book, Category, Creator, Contributor


class Command(BaseCommand):
    def handle(self, *args, **options):

        CONTRIBUTORS = ['Internet Archive', 'New York Public Library', 'Robarts - University of Toronto',
                        'Sikh National Archives of Canada', 'The Library of Congress',
                        'The LuEsther T Mertz Library, the New York Botanical Garden',
                        'University of California Libraries', 'Unknown']
        CATEGORIES = ['Afghan Wars', 'Band Sigha Bahdara, 1670-1716?', 'Bhagats', 'Caste - India Punjab',
                      'Coins, Indic', 'Dorothy Field', 'Forests and forestry - India Punjab',
                      'Lawrence, Henry Montgomery, Sir, 1806-1857', 'Muslims -- India',
                      'Panjabis (South Asian people)', 'Plants', 'Punjab - History',
                      'Ranjit Singh, Maharaja of the Punjab, 1780-1839', 'Sikh', 'Sikh History',
                      'Sikhism', 'Sikhs Biography', 'Unspecified']

        CREATORS = ["A cavalry officer", "Agnihotri, Dr: Harbans Lal", "AgraVig, Editor Tej Kaur",
                    "Ahluwalia, Jasbir Singh",
                    "Ahluwalia, M. L.", "Alag, Sarup Singh", "Amol, Sarmukh Singh", "Amol, S. S.",
                    "Anand, Balwant Singh",
                    "Aoujla, Karamjit Singh", "Arfi, Niranjan", "Arora, Dr: Fauja Singh & A. C.", "Arora, Editor: A C",
                    "A, Shamsher Singh MRani, Illustrations  Phulan", "Ashok, Editor Shamsher Singh",
                    "Ashok, Shamsher Singh",
                    "Atwal, Bakhshish Singh", "Azad, Gyani Mohan Singh Ji", "Bahree, Dr. Seeta Raam",
                    "Bains, Hardial Singh",
                    "Ballagan, Kartar Singh", "Bal, Surji Singh", "Bamber, Charles James, 1855-", "Banarji, I. B.",
                    "Banga, Edi Indu", "Barrier, Edi Pashaura Singh & N Gerald", "Batalwi, Ahemad Shah",
                    "Bawa, Prof. Harkishan Singh & D.S.", "Bedi, Gursharan Singh", "Bhaji, Harbajhan Singh",
                    "Bhangu, Rathan Singh", "Bhangu, Rattan Singh", "Bhatia, Editor Krishan Lal Sharma Narinder Kaur",
                    "Bir, Raghbir Singh", "Brahmjagdish Singh", "Callewaret, Winand M.",
                    "Chack, Bhai Jivan Singh JaiSingh, Editor Guriqbal", "Chatrik, Lala Dhani Ram",
                    "Commission, Canadian Human Rights", "Commitee, iromani Gurdawara Parbandhak",
                    "Commitee, Shiromani Gurdawara Parbandhak", "Com., Shromani Gurudwara Prabadhak",
                    "Cooper, Frederick, 1826 or 7-1869", "Cunningham, J.D.", "Daljit Singh, Kharak Singh",
                    "Dard, Edi Hira Singh",
                    "Darshi, A.R.", "Data, Piara Singh", "Datta, V N", "Davies, Robin", "Dalip Singh",
                    "Deol, Doctor Gurdev Singh", "Deol, Dr: Gurdev Singh", "Deol, G S", "Deol, G.S.",
                    "Deol, Gurdev Singh",
                    "Dhaliwal, Amar Singh", "Dheer, Kudeep Singh", "Dheer, Kuldeep Singh", "Dhillon, Bechint Singh",
                    "Dhillon, Harish", "Dilbar, Daya Singh", "Dilgeer, Dr. Harjinder Singh", "Dilgeer, Harjinder Singh",
                    "D., Jarnail Singh Ph.", "Doabia, Harbans Singh", "Dorothy Field", "Dr. Ernest Trumpp",
                    "Dr. Ganga Singh M.A., Ph.DSingh, Late Prof. Puran", "Duggal, Kartar Singh", "Duggal, K.S.",
                    "Duleh, Hoshiar Singh", "Dusandh, Katar Singh",
                    "Economist, an officer of practical experience in the Punjab",
                    "Field, Dorothy, 1944-", "Frank, Jeenu", "Gahunia, Narinder Singh", "Gandharv, Sant Sarwan Singh",
                    "Gardner, AlexanderBaddan, Editor Baldev Singh", "Ghuman, Dr:Bikram Singh",
                    "Giani, Editor: Sita Ram Kohli & Sewa Singh", "Giani Maan Singh Jhour",
                    "Giani Partap Singh ji Jotshi",
                    "Gibbon, Frederick P", "Gill, Mohinder Kaur", "Gill, Raaj", "Gill, Tarlochan Singh",
                    "Gill, Tirlochan Singh",
                    "Gogoani, Inderjit Singh", "Greenlees, Duncan", "Grewal, Garry", "Grewal, Jaswinder Singh",
                    "Grewal, J S",
                    "Grewal, J.S.", "Griffin, Lepel Henry, Sir, 1840-1908", "Grover, Editor B. R.",
                    "Gujjarwal, Nahar Singh",
                    "Gujrati, Mehar SinghPadam, Editor Piara Singh", "Gupta, Editor: M.G.", "Gupta, Hari Ram",
                    "Gurmail Singh Sidhu, K.L. Garg", "Hami, Harbajhan Singh", "Hans, S S",
                    "Harbajhan Singh, Satnam Singh",
                    "Harnam Singh Shaan", "Heera", "Bhagat Singh", "Henry, G. A.", "Hess, Harmn", "Hira, Bhagat Singh",
                    "Historian, Karam Singh", "Hiteshi, Tara Singh", "Hoti, Baba Prem Singh",
                    "Ibbetson, Denzil, Sir, 1847-1908",
                    "Jaggi, Editor. Rattab Singh", "Jaggi, Gursharan Kout", "Jaggi, Rattan Singh",
                    "Jakhmi, Karam Singh",
                    "Jaspal, Brigadier Partap Singh", "Jaspal, Brig Partap Singh", "Jass, Jaswant Singh",
                    "Jasuja, Gurcharan Singh", "Jhaor, Maan Singh", "Ji, Akali Kaur Singh", "Ji, Amar Singh",
                    "Ji, Bhai Gurdas",
                    "Ji, Bhai Nand Lal", "Ji, Bhai Sahib Bhai Veer Singh", "Ji, Bhai Sahib Dr. Veer Sungh",
                    "Ji, Bhai Sher Singh",
                    "Ji, Bhai Vir Singh", "Ji, Editor Lal Singh", "Ji, Giani Gian Singh", "Ji, Mahant Ganesha Singh",
                    "Ji, Prof. Sahib Singh", "Ji, Saint Kirpal Singh", "Ji, Shahid Bhai Mani Singh",
                    "Ji, Sohdi Teja Singh",
                    "Ji, Sri Maan Giani Singh", "Johar, Srinder Singh", "Johar, Surindar Singh", "Johnston, Hugh",
                    "Josh, Mahindar Singh", "Josh, Sohan Singh", "Kalsi, Nirmal Singh", "Kanwal, Jaswant Singh",
                    "Kapoor, Dr Tarbhan", "Kapoor, Ediited Satish K.", "Kapoor, Prithipal Singh", "Karm SIngh Zakhmi",
                    "Kaura, Kulbir Singh", "Kaur, Editor Gurnam", "Kaur, Harbans", "Kaur, Mrs Manjit", "Kaur, Simran",
                    "Kaur, Sukhwinder", "Kavishar, Sardul Singh", "Khalsa, Baljit Singh", "Khalsa", "Giani Avtar Singh",
                    "Khalsa Tract Society", "Khalsa Tract Society.*", "Khalsi, Takhar Singh", "Khilnani, N M",
                    "Khokar, Dr. Kalwant Singh", "Kirpal-Singh, Saint", "Kohli, Dr. Jai Dev Singh",
                    "Kohli, Dr: Kuwant Kaur",
                    "Kohli, Dr: S. S.", "Kohli, Dr. Surindar Singh", "Kohli, Dr Surinder Singh",
                    "Kohli, Surindar Singh",
                    "Komal, Dann Singh", "Kushta, Maula BakhashSingh, Editor: Gurmukh", "Kussa, Shivcharan Jaggi",
                    "Kussa, Shivcharan", "Lahore. Central Museum", "Lal, Kanaheeaa", "Latif, Muhamad",
                    "Latif, Syad Muhammad",
                    "Maan, Principal Seva", "Maan, Principal Sewa Singh", "Maan, Sewa Singh", "Maan, Tejwant Singh",
                    "M.A, Balkar Singh", "M.A.B.T., Gyani Amar SinghAlag, Sarup Singh", "Macauliffe, Max Arthur",
                    "Makin, Gurbachan Singh", "Mann, Pardeep Singh Nagra & Parminder Kaur", "Mansukhani, G S",
                    "Mansukhani, Ramesh Chander Dogra & Dr. Gobind Singh", "M.a., Prof. Gurcharan Singh",
                    "Giani Sant Singh",
                    "Maskeen, Sant Singh", "Masukhani, Gobind Singh", "M.A., Teja Singh", "MBA, Amarjit Singh",
                    "Mcleod, W H",
                    "McMullen, Clarence O.", "M.G.Gupta, Editor:", "Minhas, Surjit Singh",
                    "Mohamad, ShahJaggi, Editor Rattan Singh", "Mohamad, ShahKohli, Editor Sita Ram", "Mullar, F. Max",
                    "Nabha, Bhai Kahan Singh", "Nankanvi, Pandhi", "Nara, Giani  Ishar Singh", "Natt, Paramjit Kaur",
                    "Nayyar, Gurbachan Singh", "Neer, Atar Singh", "Nekee, Gurnek Singh", "Nijjar, B. S.",
                    "Noor, Nirmal Singh",
                    "Nupri, Nand Lal", "Nyrop, Richard F.", "Oherio, Mrs. Mridula", "Others, Fauja Singh &",
                    "Others, Milton Isreal &", "Padam, Piara Singh", "Padhm, Pyara Singh", "Parry, Roy Edgardo",
                    "Parwana, Jsawant Singh", "Patwari, Karam Singh", "Paul, Mohinder Singh",
                    "Payne, C. H. (Charles Herbert)",
                    "Phul, Gurdial Singh", "Principal, Surjit Singh", "Prinsep, Henry Thoby, 1793-1878",
                    "Punjab (India). Forest Dept", "Puran Singh", "Puri, Dr: Gopal Singh", "Puri, Shamsher Singh",
                    "Rai, Daulat",
                    "Rai, Gurnam Singh", "Rajshekar, V.T.", "Ram, Bhai Sahij", "Randhawa, G.S.",
                    "Ras, Giani Nihal Singh",
                    "Ras, Principal Nihal Singh", "Rattab, Harbajhan Singh", "Ray, Niharranjan", "Rekhi, Gurnam Singh",
                    "Roop, Harinder Singh", "Ruggles, John, 1827", "Sabar, Editor: Jasbir Singh", "Sabar, Sadhu Singh",
                    "Safir, Preetam Singh", "Safri, Charan Singh", "Sagoo, Harbans Kaur", "Sahni, Balraj",
                    "Sahrai, Harnam Dass",
                    "Sambhi, W. Owen Cole & Piara Singh", "Sandhu, Balbir Singh", "Sandhu, Jasbir Singh",
                    "Schopflin, George",
                    "Seetal, Sohan Singh", "Sehgal, Dr. Manmohan", "Sehgal, Ojagar Singh", "Sethi, Joginder Singh",
                    "Shahdi, Shek",
                    "Shaheed, Charan Singh", "Shahid, Bhai Rathan Singh Bhangu", "Shan, Dr: Harnam Singh",
                    "Shan, Harnam Singh",
                    "Sharma, Editor Krishan Lal", "Sharma, G. L.", "Sharma, Krishan Lal", "Shaunki, Gulzar Singh",
                    "Sher Singh",
                    "Singha, H.S.", "Singh, Ajmer", "Singh, Amar", "Singh, Anoop", "Singh, Atma", "Singh, Baghel",
                    "Singh, Balbir",
                    "Singh, Balkar", "Singh, Balwinder", "Singh, Bhag", "Singh, Bhagat", "Singh, Bhagat  Lakshman",
                    "Singh, Bhai Har Simran", "Singh, Bhai Jodh", "Singh, Bhai Joid", "Singh, Bhai Kan",
                    "Singh, Bhai Kaur",
                    "Singh, Bhai Maggar", "Singh, Bhai Raam", "Singh, Bhai Randheer", "Singh, Bhai Randhir",
                    "Singh, Bhai Sahab Randheer", "Singh, Bhai Sahib Bhai Sher", "Singh, Bhai Sahib Randheer",
                    "Singh, Bhai Sahib Ranthir", "Singh, Bhai Vir", "Singh, Braham Jagdish", "Singh, Dalbir",
                    "Singh, Dalip",
                    "Singh, Daljeet", "Singh, Dhanna", "Singh, Dharam", "Singh, Dr: Avtar", "Singh, Dr: Balkar",
                    "Singh, Dr. Balkar", "Singh, Dr Bhagat", "Singh, Dr: Dewan", "Singh, Dr: Diwan", "Singh, Dr: Fauja",
                    "Singh, Dr: Fauja Singh & Taran", "Singh, Dr: Ganda", "Singh, Dr Gopal", "Singh, Dr. Gopal",
                    "Singh, Dr: Gurcharan", "Singh, Dr: Harbhajan", "Singh, Dr. JagirAhluwhalia, Dr. Jasbir Singh",
                    "Singh, Dr: Jaspal", "Singh, Dr: Kartar", "Singh, Dr Kirpal", "Singh, Dr: Kuwant",
                    "Singh, Dr. Mohinder",
                    "Singh, Dr. Ram", "Singh, Dr: Santokh", "Singh, Dr: Sher", "Singh, Dr: Tara", "Singh, Dr:Taran",
                    "Singh, Dr: Taran", "Singh, Dr: Tarlochan", "Singh, Dr: Tirlochan", "Singh, Dr: Wazir",
                    "Singh, Ed Giani Pritam", "Singh, Edi Balwinderpal", "Singh, Edi Fauja", "Singh, Ediited: Taran",
                    "Singh, Edi Prof Hari", "Singh, Edi Sewa Singh & Gursagar",
                    "Singh, Edi Surjit Singh & Balwinderpal",
                    "Singh, Editor: Dr Anokh", "Singh, Editor: Fauja", "Singh, Editor: Giani Gurdit",
                    "Singh, Editor Gurbachan Singh Talib & Attar", "Singh, Editor Kharak", "Singh, Editor Roop",
                    "Singh, Editor Taran", "Singh, Ed Pritam", "Singh, Gajinder", "Singh, Ganda", "Singh, Ganga",
                    "Singh, Giani Amar", "Singh, Giani Bhajan", "Singh, Giani Gian", "Singh, Giani Gurdit",
                    "Singh, Giani Harbans",
                    "Singh, Giani Harkewal", "Singh, Giani  Ishar", "Singh, Giani Kirpal", "Singh, Giani Mohan",
                    "Singh, Giani Narain", "Singh, Gianin Tarlok", "Singh, Giani Partap", "Singh, Giani Pritam",
                    "Singh, Giani Tarlok", "Singh, Giani Udham", "Singh, Gurbachan Singh Nayyar & Sukhdial",
                    "Singh, Gurbakhash",
                    "Singh, Gurbakhsh", "Singh, Gurbaksh", "Singh, Gurcharan", "Singh, Gurcharan Jit", "Singh, Gurdial",
                    "Singh, Gurmit", "Singh, Gyani Ishwar", "Singh, Harbajhan", "Singh, Harbans", "Singh, Harbhajan",
                    "Singh, Harbhans", "Singh, Harchand", "Singh, Harcharan", "Singh, Har Dev", "Singh, Harikishan",
                    "Singh, Harkirat", "Singh, Harkishan", "Singh, Himat", "Singh, I J", "Singh, Jagjit", "Singh, Jodh",
                    "Singh, Kanwar Jit", "Singh, Kapur", "Singh, KapurSingh, Madanjit Kaur & Piar", "Singh, Karnail",
                    "Singh, Kavi SewaSingh, Giani Garja", "Singh, Kesar", "Singh, Khuswant", "Singh, Khuwshwant",
                    "Singh, Kirpal",
                    "Singh, Kishan", "SINGH, KOIR", "Singh, Kulvant", "Singh, Kushwant", "Singh, L M Joshi & Jodh",
                    "Singh, Malwinder Jit Singh & Harinder", "Singh, Manjeet", "Singh, Master Mehtaab", "Singh, Mehal",
                    "Singh, M. L. Ahluwalia & Dr: Kirpal", "Singh, Mohinderjit", "Singh, Nanak", "Singh, Naraan",
                    "Singh, Narinder Pal", "Singh, Nikky-Guninder Kaur", "Singh, N Iqbal", "Singh, Nirmal",
                    "Singh, Patwant",
                    "Singh, Piar", "Singh, Preetam", "Singh, Pr Harbhajan", "Singh, Principal Amar",
                    "Singh, Principal Dial",
                    "Singh, Principal Gurdev", "Singh, Principal Harbhajan", "Singh, Principal Nahar",
                    "Singh, Principal Niranjan", "Singh, Prof: Harbans", "Singh, Prof: Harikishan",
                    "Singh, Prof; Joginder", "Singh, Prof: Joginder", "Singh, Prof Kartar", "Singh, Prof: Mohan",
                    "Singh, Prof: Pritam", "Singh, Prof: Puran", "Singh, Prof: Sahib", "Singh, Prof. Sahib",
                    "Singh, Prof. Teja",
                    "Singh, Puran", "Singh, Puran, 1881-1931", "Singh, Raagi Gurcharan", "Singh, Rachhpal",
                    "Singh, Ragi Gurcharan", "Singh, Rajinder", "Singh, Raminder", "Singh, Sahib", "Singh, S. Amar",
                    "Singh, Sangat", "Singh, Sant Waryam", "Singh, Sardar Narain", "Singh, Sardul", "Singh, Sarwan",
                    "Singh, Satbir", "Singh, Satnam", "Singh, S Bishan", "Singh, S. Charan", "Singh, Seva",
                    "Singh, S. Harchand",
                    "Singh, Singh Sahib Giani Mani", "Singh, Sir Joginder Singh & Daljit", "Singh, S Manmohan",
                    "Singh, S. Narain",
                    "Singh, Sodhi Teja", "Singh, Soobadar Bugal", "Singh, Stinder", "Singh, Sub. Baghel",
                    "Singh, Subedar Bhagal",
                    "Singh, Sukhchain", "Singh, Sukhdiyal", "Singh, Taran", "Singh, Udham", "Singh, Wazir",
                    "Sodhi, Teja Singh",
                    "Sohan Singh, of Gujranwala", "Steel, Flora Annie Webster, 1847-1929",
                    "Sujjion, Subedar Dharam SunghSingh, Jaspinder", "Sukha, Harjinder Singh Jinda Sukhdev Singh",
                    "Sungh, Gursaran", "Talib, Fauja Singh & Gurbachan Singh", "Talib, Gurbachan Singh",
                    "Talvaada, Bhai Talvinder Singh Ji", "Talvadha, Bhai Joginder Singh",
                    "Talwada, Bhai Sahab Joginder Singh",
                    "Talwara, Bhai Joginder Singh", "Talwara, Joginder Singh", "Tatelay, Saint Singh",
                    "Tatla, Sant Singh",
                    "Tatle, Santa Singh", "Teeka, Faridkot Wala", "Teg, Giani Harbans Singh", "Thakur Singh",
                    "Tiwari, Dr: Vishav Nath", "Tiwari, Vishwa Nath", "Trumpp, Ernst, 1828-1885",
                    "Udassi, Gobind Singh Nirmal",
                    "Unknown", "Varma, Dr: Devinder Kumar",
                    "Varpal, Jathedar Udham SinghDilgeer, Editor Harjinder Singh",
                    "Vaswani, Thanwardas Lilaram", "Waheeduddin, Fakir Syed", "Waheedudin, Faqir Sayad",
                    "Wikeley, J. M",
                    "Zibran Khaleel"]

        TITLES = ["Katha Kirtan", "Adi Sri Guru Granth Sahib Darshan Nirney Steek Vol.6", "Sri Guru Granth Prakash ",
                  "Jiwan Anubhav", "Adi Sri Guru Granth Sahib Darshan Nirney Steek Volume 3", "Tarikh E Panjab",
                  "Sri Guru Panth Parkash ", "Sant Ka Marg", "Gurmat Chanan",
                  "HISTORY OF THE SIKHS: SIKH DOMINATION OF THE MUGHAL EMPIRE VOL 3", "Prachin Sao Sakhi",
                  "Keewan Katha-Guru Amar Das Ji", "Sri Guru Granth Sahib Darpan  Vol.7",
                  "Adi Sri Guru Granth Sahib Darshan Nirney Steek Vol.1", "Bahadur Ranjit Kaur",
                  "Panjab De Parmukh Sahitkar", "Sade Gurdev", "Manukhta De Guru: Guru Gobind Singh Ji",
                  "Japuji De Punj Khand ", "Bole Shekh Frid", "Gurmat Vairag Darshan", "Guru Nanak's Japuji",
                  "Annual Rapport", "1984 Breaking The Silence", "Karak Kaleje Mahe",
                  "Canadian Sikhs Part 1 And Komagata Maru Massacre", "Sikh Chintan Anusar Sewa Da Sankalp",
                  "Guru Amar Das - Jeewan Ate Chintan", "Guru Ka Bagh", "Chautha Pad ",
                  "Eternal Glory Of Guru Arjan Partakh Har", "Panjab And The Lion Of Panjab", "Machhiwara",
                  "The Encyclopaedia Of Sikhism Vol.2", "Panjabi Maharaja", "Ratna Ratan Padarath",
                  "Sri Guru Bani Prakash Volume 2", "Darshan Sri Guru Granth Sahib ",
                  "Sri Guru Granth Sahib: English And Punjabi Translation Vol. 4",
                  "Guru Granth Sahib Steeks-Vol.4 Ego (Haumi)", ]

        if Book.objects.count() == 0:
            for contributor in CONTRIBUTORS:
                Contributor.objects.create(name=contributor)
            for category in CATEGORIES:
                Category.objects.create(name=category)
            for creator in CREATORS:
                Creator.objects.create(name=creator)

            contributors_ids = list(Contributor.objects.values_list('id', flat=True))
            creators_ids = list(Creator.objects.values_list('id', flat=True))
            categories_ids = list(Category.objects.values_list('id', flat=True))

            for book in TITLES:
                Book.objects.create(name=book, contributor_id=random.choice(contributors_ids),
                                    creator_id=random.choice(creators_ids), category_id=random.choice(categories_ids),
                                    num_copies=random.choice([1, 2]), published=str(random.randint(1850, 1990)),
                                    e_book=random.choice([True, False]), can_be_processed=True)
