# Generated by Django 2.2.1 on 2019-05-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('num_copies', models.IntegerField(default=1, help_text='Number of physical copies held by the library')),
                ('scanned', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='book/')),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='cover/')),
                ('book_type', models.IntegerField(blank=True, choices=[(1, 'Book'), (2, 'Magazine'), (3, 'Document')], null=True)),
                ('panjabi', models.BooleanField(default=False, help_text='Select it if book is on Punjabi')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.Contributor')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.Creator')),
            ],
        ),
    ]
