# Generated by Django 2.2.1 on 2019-05-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_auto_20190504_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
