# Generated by Django 2.2.1 on 2019-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ocr_processed',
            field=models.BooleanField(default=False),
        ),
    ]
