# Generated by Django 2.2.1 on 2019-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_book_ocr_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
