# Generated by Django 2.2.1 on 2019-05-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0008_book_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
    ]
