# Generated by Django 2.2.1 on 2019-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_auto_20190506_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='can_be_processed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='fail_reason',
            field=models.TextField(blank=True, help_text="If OCR can't open/read/process file", null=True),
        ),
    ]
