# Generated by Django 2.2.1 on 2019-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_auto_20190507_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories_icons/'),
        ),
    ]
