# Generated by Django 2.2.1 on 2019-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='e_book',
            field=models.BooleanField(default=False),
        ),
    ]
