# Generated by Django 2.2.1 on 2019-05-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0013_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.Book'),
        ),
    ]
