# Generated by Django 2.2.1 on 2019-05-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    def add_about_page(apps, schema_editor):
        pages = apps.get_model('ui', 'CustomPage')
        if pages.objects.count() == 0:
            pages.objects.create(name='About', content="""
<p><strong>Sikh National Archives of Canada: Preserving the past building the future.</strong></p>
<p>Established in 1999 as a registered charity, Sikh National Archives of Canada&rsquo;s (SNAC) mission has been to collect, store and archive historic, religious, and cultural literature, scriptures, books, articles, (including published and unpublished) materials relating to the Sikh religion and Canadian Sikh experience. This vast collection promotes awareness and understanding of the cultural heritage and values of the Sikh Canadians.</p>
<p>SNAC is in the process of building a multi-purpose website which will allow easy access to their entire physical collection which since 1984 has been housed at the SNAC head office in Ottawa. The first phase of this website is complete but in order to complete this vast project we need YOUR support. Upon completion you will be able to:</p>
<p>&bull; Read the entire SNAC collection online<br />&bull; Search catalogued item listings with complete descriptive details<br />&bull; Search collection catalogue using title, author, publisher, subject, place<br />&bull; Search any word or term inside individual books, magazines, articles<br />&bull; Fully search Panjabi books, magazines, newspapers and documents<br />&bull; Share items easily via social media<br />&bull; Use the flip book reader to make books easily readable<br />&bull; Use the read aloud feature for greater accessibility<br />&bull; Download books in different formats (Online Book Reader, PDF, Plain Text, ePub, Djvu, MOBI or Kindle).</p>
<p><a href="http://donateyourdesktop.ca/wp-content/uploads/edd/2014/02/SNAC1.jpg"><img src="http://donateyourdesktop.ca/wp-content/uploads/edd/2014/02/SNAC1-300x153.jpg" alt="SNAC1" height="153" class="alignnone size-medium wp-image-667" width="300" /></a></p>
<p>&nbsp;</p>
<p><strong>When you support Sikh National Archives of Canada you are supporting:</strong></p>
<p><strong>Inclusion</strong><br />Sikh National Archives creates a more inclusive society by documenting, preserving, and sharing stories<br />that represent the unique and diverse experiences of Canadian Sikhs.</p>
<p><strong>Innovation</strong><br />Our innovative approach will allow individuals access to a wealth of digital content. This can be used as a tool for empowerment and identity formation.</p>
<p><strong>Grassroots</strong><br />More than 95% of our financial support comes from individual donors just like you. The organization is run by a small number of dedicated volunteers.</p>
<p><strong>A vision for the future</strong><br />We believe that Canadian Sikh narrative is an integral part of Canadian history and our mission is to ensure that Canadian Sikh stories are documented, preserved,and made easily available for greater public good.</p>            
            """)

    dependencies = [
        ('ui', '0004_custompage'),
    ]

    operations = [
        migrations.RunPython(add_about_page),
    ]

