# Generated by Django 2.2.1 on 2019-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
