# Generated by Django 2.2.1 on 2019-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_auto_20190510_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
